/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1CountriesVisitedCitiesGet200ResponseDataInner {
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "cities", skip_serializing_if = "Option::is_none")]
    pub cities: Option<Vec<models::ApiV1CountriesVisitedCitiesGet200ResponseDataInnerCitiesInner>>,
}

impl ApiV1CountriesVisitedCitiesGet200ResponseDataInner {
    pub fn new() -> ApiV1CountriesVisitedCitiesGet200ResponseDataInner {
        ApiV1CountriesVisitedCitiesGet200ResponseDataInner {
            country: None,
            cities: None,
        }
    }
}

