/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1StatsGet200ResponseYearlyStatsInnerMonthlyDistanceKm {
    #[serde(rename = "january", skip_serializing_if = "Option::is_none")]
    pub january: Option<f64>,
    #[serde(rename = "february", skip_serializing_if = "Option::is_none")]
    pub february: Option<f64>,
    #[serde(rename = "march", skip_serializing_if = "Option::is_none")]
    pub march: Option<f64>,
    #[serde(rename = "april", skip_serializing_if = "Option::is_none")]
    pub april: Option<f64>,
    #[serde(rename = "may", skip_serializing_if = "Option::is_none")]
    pub may: Option<f64>,
    #[serde(rename = "june", skip_serializing_if = "Option::is_none")]
    pub june: Option<f64>,
    #[serde(rename = "july", skip_serializing_if = "Option::is_none")]
    pub july: Option<f64>,
    #[serde(rename = "august", skip_serializing_if = "Option::is_none")]
    pub august: Option<f64>,
    #[serde(rename = "september", skip_serializing_if = "Option::is_none")]
    pub september: Option<f64>,
    #[serde(rename = "october", skip_serializing_if = "Option::is_none")]
    pub october: Option<f64>,
    #[serde(rename = "november", skip_serializing_if = "Option::is_none")]
    pub november: Option<f64>,
    #[serde(rename = "december", skip_serializing_if = "Option::is_none")]
    pub december: Option<f64>,
}

impl ApiV1StatsGet200ResponseYearlyStatsInnerMonthlyDistanceKm {
    pub fn new() -> ApiV1StatsGet200ResponseYearlyStatsInnerMonthlyDistanceKm {
        ApiV1StatsGet200ResponseYearlyStatsInnerMonthlyDistanceKm {
            january: None,
            february: None,
            march: None,
            april: None,
            may: None,
            june: None,
            july: None,
            august: None,
            september: None,
            october: None,
            november: None,
            december: None,
        }
    }
}

