/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1CountriesVisitedCitiesGet200ResponseDataInnerCitiesInner {
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Number of points in the city
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<i32>,
    /// Timestamp of the last point in the city in seconds since Unix epoch
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i32>,
    /// Number of minutes the user stayed in the city
    #[serde(rename = "stayed_for", skip_serializing_if = "Option::is_none")]
    pub stayed_for: Option<i32>,
}

impl ApiV1CountriesVisitedCitiesGet200ResponseDataInnerCitiesInner {
    pub fn new() -> ApiV1CountriesVisitedCitiesGet200ResponseDataInnerCitiesInner {
        ApiV1CountriesVisitedCitiesGet200ResponseDataInnerCitiesInner {
            city: None,
            points: None,
            timestamp: None,
            stayed_for: None,
        }
    }
}

