/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1PointsPostRequestProperties {
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "horizontal_accuracy", skip_serializing_if = "Option::is_none")]
    pub horizontal_accuracy: Option<f64>,
    #[serde(rename = "vertical_accuracy", skip_serializing_if = "Option::is_none")]
    pub vertical_accuracy: Option<f64>,
    #[serde(rename = "altitude", skip_serializing_if = "Option::is_none")]
    pub altitude: Option<f64>,
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<f64>,
    #[serde(rename = "speed_accuracy", skip_serializing_if = "Option::is_none")]
    pub speed_accuracy: Option<f64>,
    #[serde(rename = "course", skip_serializing_if = "Option::is_none")]
    pub course: Option<f64>,
    #[serde(rename = "course_accuracy", skip_serializing_if = "Option::is_none")]
    pub course_accuracy: Option<f64>,
    #[serde(rename = "track_id", skip_serializing_if = "Option::is_none")]
    pub track_id: Option<String>,
    #[serde(rename = "device_id", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
}

impl ApiV1PointsPostRequestProperties {
    pub fn new() -> ApiV1PointsPostRequestProperties {
        ApiV1PointsPostRequestProperties {
            timestamp: None,
            horizontal_accuracy: None,
            vertical_accuracy: None,
            altitude: None,
            speed: None,
            speed_accuracy: None,
            course: None,
            course_accuracy: None,
            track_id: None,
            device_id: None,
        }
    }
}

