/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1PointsGet200ResponseInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "battery_status", skip_serializing_if = "Option::is_none")]
    pub battery_status: Option<f64>,
    #[serde(rename = "ping", skip_serializing_if = "Option::is_none")]
    pub ping: Option<f64>,
    #[serde(rename = "battery", skip_serializing_if = "Option::is_none")]
    pub battery: Option<f64>,
    #[serde(rename = "tracker_id", skip_serializing_if = "Option::is_none")]
    pub tracker_id: Option<String>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(rename = "altitude", skip_serializing_if = "Option::is_none")]
    pub altitude: Option<f64>,
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[serde(rename = "velocity", skip_serializing_if = "Option::is_none")]
    pub velocity: Option<f64>,
    #[serde(rename = "trigger", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<String>,
    #[serde(rename = "bssid", skip_serializing_if = "Option::is_none")]
    pub bssid: Option<String>,
    #[serde(rename = "ssid", skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
    #[serde(rename = "connection", skip_serializing_if = "Option::is_none")]
    pub connection: Option<String>,
    #[serde(rename = "vertical_accuracy", skip_serializing_if = "Option::is_none")]
    pub vertical_accuracy: Option<f64>,
    #[serde(rename = "accuracy", skip_serializing_if = "Option::is_none")]
    pub accuracy: Option<f64>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<f64>,
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<f64>,
    #[serde(rename = "inrids", skip_serializing_if = "Option::is_none")]
    pub inrids: Option<Vec<String>>,
    #[serde(rename = "in_regions", skip_serializing_if = "Option::is_none")]
    pub in_regions: Option<Vec<String>>,
    #[serde(rename = "raw_data", skip_serializing_if = "Option::is_none")]
    pub raw_data: Option<String>,
    #[serde(rename = "import_id", skip_serializing_if = "Option::is_none")]
    pub import_id: Option<String>,
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "geodata", skip_serializing_if = "Option::is_none")]
    pub geodata: Option<String>,
    #[serde(rename = "visit_id", skip_serializing_if = "Option::is_none")]
    pub visit_id: Option<String>,
}

impl ApiV1PointsGet200ResponseInner {
    pub fn new() -> ApiV1PointsGet200ResponseInner {
        ApiV1PointsGet200ResponseInner {
            id: None,
            battery_status: None,
            ping: None,
            battery: None,
            tracker_id: None,
            topic: None,
            altitude: None,
            longitude: None,
            velocity: None,
            trigger: None,
            bssid: None,
            ssid: None,
            connection: None,
            vertical_accuracy: None,
            accuracy: None,
            timestamp: None,
            latitude: None,
            mode: None,
            inrids: None,
            in_regions: None,
            raw_data: None,
            import_id: None,
            city: None,
            country: None,
            created_at: None,
            updated_at: None,
            user_id: None,
            geodata: None,
            visit_id: None,
        }
    }
}

