/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1CountriesVisitedCitiesGet400Response {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl ApiV1CountriesVisitedCitiesGet400Response {
    pub fn new() -> ApiV1CountriesVisitedCitiesGet400Response {
        ApiV1CountriesVisitedCitiesGet400Response {
            error: None,
        }
    }
}

