/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1SettingsGet200Response {
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<models::ApiV1SettingsGet200ResponseSettings>>,
}

impl ApiV1SettingsGet200Response {
    pub fn new() -> ApiV1SettingsGet200Response {
        ApiV1SettingsGet200Response {
            settings: None,
        }
    }
}

