/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1PointsTrackedMonthsGet200ResponseInner {
    /// Year in YYYY format
    #[serde(rename = "year")]
    pub year: i32,
    #[serde(rename = "months")]
    pub months: Vec<String>,
}

impl ApiV1PointsTrackedMonthsGet200ResponseInner {
    pub fn new(year: i32, months: Vec<String>) -> ApiV1PointsTrackedMonthsGet200ResponseInner {
        ApiV1PointsTrackedMonthsGet200ResponseInner {
            year,
            months,
        }
    }
}

