/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1StatsGet200ResponseYearlyStatsInner {
    #[serde(rename = "year")]
    pub year: i32,
    #[serde(rename = "totalDistanceKm")]
    pub total_distance_km: f64,
    #[serde(rename = "totalCountriesVisited")]
    pub total_countries_visited: f64,
    #[serde(rename = "totalCitiesVisited")]
    pub total_cities_visited: f64,
    #[serde(rename = "monthlyDistanceKm")]
    pub monthly_distance_km: Box<models::ApiV1StatsGet200ResponseYearlyStatsInnerMonthlyDistanceKm>,
}

impl ApiV1StatsGet200ResponseYearlyStatsInner {
    pub fn new(year: i32, total_distance_km: f64, total_countries_visited: f64, total_cities_visited: f64, monthly_distance_km: models::ApiV1StatsGet200ResponseYearlyStatsInnerMonthlyDistanceKm) -> ApiV1StatsGet200ResponseYearlyStatsInner {
        ApiV1StatsGet200ResponseYearlyStatsInner {
            year,
            total_distance_km,
            total_countries_visited,
            total_cities_visited,
            monthly_distance_km: Box::new(monthly_distance_km),
        }
    }
}

