/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1AreasGet200ResponseInner {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "latitude")]
    pub latitude: f64,
    #[serde(rename = "longitude")]
    pub longitude: f64,
    #[serde(rename = "radius")]
    pub radius: f64,
}

impl ApiV1AreasGet200ResponseInner {
    pub fn new(id: i32, name: String, latitude: f64, longitude: f64, radius: f64) -> ApiV1AreasGet200ResponseInner {
        ApiV1AreasGet200ResponseInner {
            id,
            name,
            latitude,
            longitude,
            radius,
        }
    }
}

