/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1OverlandBatchesPostRequest {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<Box<models::ApiV1OverlandBatchesPostRequestGeometry>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::ApiV1OverlandBatchesPostRequestProperties>>,
}

impl ApiV1OverlandBatchesPostRequest {
    pub fn new() -> ApiV1OverlandBatchesPostRequest {
        ApiV1OverlandBatchesPostRequest {
            r#type: None,
            geometry: None,
            properties: None,
        }
    }
}

