/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1CountriesVisitedCitiesGet200Response {
    /// Array of countries and their visited cities
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::ApiV1CountriesVisitedCitiesGet200ResponseDataInner>>,
}

impl ApiV1CountriesVisitedCitiesGet200Response {
    pub fn new() -> ApiV1CountriesVisitedCitiesGet200Response {
        ApiV1CountriesVisitedCitiesGet200Response {
            data: None,
        }
    }
}

