/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1PointsPostRequestGeometry {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "coordinates", skip_serializing_if = "Option::is_none")]
    pub coordinates: Option<Vec<f64>>,
}

impl ApiV1PointsPostRequestGeometry {
    pub fn new() -> ApiV1PointsPostRequestGeometry {
        ApiV1PointsPostRequestGeometry {
            r#type: None,
            coordinates: None,
        }
    }
}

