/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1SettingsPatchRequest {
    #[serde(rename = "route_opacity", skip_serializing_if = "Option::is_none")]
    pub route_opacity: Option<f64>,
    #[serde(rename = "meters_between_routes", skip_serializing_if = "Option::is_none")]
    pub meters_between_routes: Option<f64>,
    #[serde(rename = "minutes_between_routes", skip_serializing_if = "Option::is_none")]
    pub minutes_between_routes: Option<f64>,
    #[serde(rename = "fog_of_war_meters", skip_serializing_if = "Option::is_none")]
    pub fog_of_war_meters: Option<f64>,
    #[serde(rename = "time_threshold_minutes", skip_serializing_if = "Option::is_none")]
    pub time_threshold_minutes: Option<f64>,
    #[serde(rename = "merge_threshold_minutes", skip_serializing_if = "Option::is_none")]
    pub merge_threshold_minutes: Option<f64>,
}

impl ApiV1SettingsPatchRequest {
    pub fn new() -> ApiV1SettingsPatchRequest {
        ApiV1SettingsPatchRequest {
            route_opacity: None,
            meters_between_routes: None,
            minutes_between_routes: None,
            fog_of_war_meters: None,
            time_threshold_minutes: None,
            merge_threshold_minutes: None,
        }
    }
}

