/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1SettingsGet200ResponseSettings {
    #[serde(rename = "route_opacity")]
    pub route_opacity: String,
    #[serde(rename = "meters_between_routes")]
    pub meters_between_routes: String,
    #[serde(rename = "minutes_between_routes")]
    pub minutes_between_routes: String,
    #[serde(rename = "fog_of_war_meters")]
    pub fog_of_war_meters: String,
    #[serde(rename = "time_threshold_minutes")]
    pub time_threshold_minutes: String,
    #[serde(rename = "merge_threshold_minutes")]
    pub merge_threshold_minutes: String,
}

impl ApiV1SettingsGet200ResponseSettings {
    pub fn new(route_opacity: String, meters_between_routes: String, minutes_between_routes: String, fog_of_war_meters: String, time_threshold_minutes: String, merge_threshold_minutes: String) -> ApiV1SettingsGet200ResponseSettings {
        ApiV1SettingsGet200ResponseSettings {
            route_opacity,
            meters_between_routes,
            minutes_between_routes,
            fog_of_war_meters,
            time_threshold_minutes,
            merge_threshold_minutes,
        }
    }
}

