/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1StatsGet200Response {
    #[serde(rename = "totalDistanceKm")]
    pub total_distance_km: f64,
    #[serde(rename = "totalPointsTracked")]
    pub total_points_tracked: f64,
    #[serde(rename = "totalReverseGeocodedPoints")]
    pub total_reverse_geocoded_points: f64,
    #[serde(rename = "totalCountriesVisited")]
    pub total_countries_visited: f64,
    #[serde(rename = "totalCitiesVisited")]
    pub total_cities_visited: f64,
    #[serde(rename = "yearlyStats")]
    pub yearly_stats: Vec<models::ApiV1StatsGet200ResponseYearlyStatsInner>,
}

impl ApiV1StatsGet200Response {
    pub fn new(total_distance_km: f64, total_points_tracked: f64, total_reverse_geocoded_points: f64, total_countries_visited: f64, total_cities_visited: f64, yearly_stats: Vec<models::ApiV1StatsGet200ResponseYearlyStatsInner>) -> ApiV1StatsGet200Response {
        ApiV1StatsGet200Response {
            total_distance_km,
            total_points_tracked,
            total_reverse_geocoded_points,
            total_countries_visited,
            total_cities_visited,
            yearly_stats,
        }
    }
}

