/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1PointsPostRequest {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "geometry")]
    pub geometry: Box<models::ApiV1PointsPostRequestGeometry>,
    #[serde(rename = "properties")]
    pub properties: Box<models::ApiV1PointsPostRequestProperties>,
}

impl ApiV1PointsPostRequest {
    pub fn new(geometry: models::ApiV1PointsPostRequestGeometry, properties: models::ApiV1PointsPostRequestProperties) -> ApiV1PointsPostRequest {
        ApiV1PointsPostRequest {
            r#type: None,
            geometry: Box::new(geometry),
            properties: Box::new(properties),
        }
    }
}

