/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};


/// struct for typed errors of method [`api_v1_photos_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1PhotosGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_photos_id_thumbnail_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1PhotosIdThumbnailGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}


pub async fn api_v1_photos_get(configuration: &configuration::Configuration, api_key: &str, start_date: &str, end_date: &str) -> Result<Vec<models::ApiV1PhotosGet200ResponseInner>, Error<ApiV1PhotosGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_api_key = api_key;
    let p_start_date = start_date;
    let p_end_date = end_date;

    let uri_str = format!("{}/api/v1/photos", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("api_key", &p_api_key.to_string())]);
    req_builder = req_builder.query(&[("start_date", &p_start_date.to_string())]);
    req_builder = req_builder.query(&[("end_date", &p_end_date.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1PhotosGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn api_v1_photos_id_thumbnail_get(configuration: &configuration::Configuration, id: &str, api_key: &str, source: &str) -> Result<models::ApiV1PhotosIdThumbnailGet200Response, Error<ApiV1PhotosIdThumbnailGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_api_key = api_key;
    let p_source = source;

    let uri_str = format!("{}/api/v1/photos/{id}/thumbnail", configuration.base_path, id=crate::apis::urlencode(p_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("api_key", &p_api_key.to_string())]);
    req_builder = req_builder.query(&[("source", &p_source.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1PhotosIdThumbnailGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

